[[headers]]
  for = "/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=14400, stale-while-revalidate=604800"
    Content-Type = "font/woff"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=14400, stale-while-revalidate=604800"
    Content-Type = "font/woff2"


[[headers]]
  for = "/*.mp4"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=14400, stale-while-revalidate=604800"
    Content-Type = "video/mp4"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200